# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-8ecZYwBrMlMeMFmtvEt-cU6z_h-EE5M
"""

from geopy.geocoders import Nominatim
import pandas as pd

import pandas as pd
from geopy.geocoders import Nominatim

def get_location_data(location):
    geolocator = Nominatim(user_agent="my_geocoder")
    location_info = geolocator.geocode(location, addressdetails=True)
    return location_info.raw if location_info else None

def create_csv(locations):
    data = []
    for location in locations:
        location_data = get_location_data(location)
        if location_data:
            data.append(location_data)

    # Filter1
    df = pd.json_normalize(data)

    #Filter2
    df_filtered = df.iloc[:, 6:-1]

    #Filter3
    df_filtered.fillna('Not Found', inplace=True)


    df_filtered.to_csv('/content/drive/MyDrive/data.csv', index=False)


locations = ["Zaharchev Winery and Distillery ", "Попова Кула", "Chateau Sopot", "Domaine Lepovo", "Vinarija Stobi", "Камник"]
create_csv(locations)

